### ISSUE TITLE
Not compatible version of Nuget when installing in portable Xamarin project

### ISSUE THREAD

**Issue by Levvy055** [CoryCharlton/CCSWE-Libraries#11]
Whenever I try to install Core NuGet I receive:
> Could not install package 'CCSWE.Core 2.0.348.3791'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Can you make it compatible?The most problematic as I see is the existence of 'Serializable'.

**Comment by CoryCharlton** [comment]
The library was originally written for .NET Full so I'm not surprised there are issues. I'll take a look and see what it will take to resolve them.

**Comment by CoryCharlton** [comment]
The 2.1.0 package I released yesterday now targets netstandard1.6, netstandard2.0, and net45. Let me know if you run into any issues.
